package com.toybeth.docto.utils

object CountrieCodes {

    val list = listOf(
        CountryCode("af", "Afghanistan (‫افغانستان‬‎)", 93),
        CountryCode("al", "Albania (Shqipëri)", 355),
        CountryCode("dz", "Algeria (‫الجزائر‬‎)", 213),
        CountryCode("as", "American Samoa", 684),
        CountryCode("ad", "Andorra", 376),
        CountryCode("ao", "Angola", 244),
        CountryCode("ai", "Anguilla", 264),
        CountryCode("ag", "Antigua and Barbuda", 268),
        CountryCode("ar", "Argentina", 54),
        CountryCode("am", "Armenia (Հայաստան)", 374),
        CountryCode("aw", "Aruba", 297),
        CountryCode("au", "Australia", 61),
        CountryCode("at", "Austria (Österreich)", 43),
        CountryCode("az", "Azerbaijan (Azərbaycan)", 994),
        CountryCode("bs", "Bahamas", 242),
        CountryCode("bh", "Bahrain (‫البحرين‬‎)", 973),
        CountryCode("bd", "Bangladesh (বাংলাদেশ)", 880),
        CountryCode("bb", "Barbados", 246),
        CountryCode("by", "Belarus (Беларусь)", 375),
        CountryCode("be", "Belgium (België)", 32),
        CountryCode("bz", "Belize", 501),
        CountryCode("bj", "Benin (Bénin)", 229),
        CountryCode("bm", "Bermuda", 441),
        CountryCode("bt", "Bhutan (འབྲུག)", 975),
        CountryCode("bo", "Bolivia", 591),
        CountryCode("ba", "Bosnia and Herzegovina (Босна и Херцеговина)", 387),
        CountryCode("bw", "Botswana", 267),
        CountryCode("br", "Brazil (Brasil)", 55),
        CountryCode("io", "British Indian Ocean Territory", 246),
        CountryCode("vg", "British Virgin Islands", 284),
        CountryCode("bn", "Brunei", 673),
        CountryCode("bg", "Bulgaria (България)", 359),
        CountryCode("bf", "Burkina Faso", 226),
        CountryCode("bi", "Burundi (Uburundi)", 257),
        CountryCode("kh", "Cambodia (កម្ពុជា)", 855),
        CountryCode("cm", "Cameroon (Cameroun)", 237),
        CountryCode("ca", "Canada", 1),
        CountryCode("cv", "Cape Verde (Kabu Verdi)", 238),
        CountryCode("bq", "Caribbean Netherlands", 599),
        CountryCode("ky", "Cayman Islands", 345),
        CountryCode("cf", "Central African Republic (République centrafricaine)", 236),
        CountryCode("td", "Chad (Tchad)", 235),
        CountryCode("cl", "Chile", 56),
        CountryCode("cn", "China (中国)", 86),
        CountryCode("cx", "Christmas Island", 61),
        CountryCode("cc", "Cocos (Keeling) Islands", 61),
        CountryCode("co", "Colombia", 57),
        CountryCode("km", "Comoros (‫جزر القمر‬‎)", 269),
        CountryCode("cd", "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)", 243),
        CountryCode("cg", "Congo (Republic) (Congo-Brazzaville)", 242),
        CountryCode("ck", "Cook Islands", 682),
        CountryCode("cr", "Costa Rica", 506),
        CountryCode("ci", "Côte d’Ivoire", 225),
        CountryCode("hr", "Croatia (Hrvatska)", 385),
        CountryCode("cu", "Cuba", 53),
        CountryCode("cw", "Curaçao", 599),
        CountryCode("cy", "Cyprus (Κύπρος)", 357),
        CountryCode("cz", "Czech Republic (Česká republika)", 420),
        CountryCode("dk", "Denmark (Danmark)", 45),
        CountryCode("dj", "Djibouti", 253),
        CountryCode("dm", "Dominica", 767),
        CountryCode("do", "Dominican Republic (República Dominicana)", 1),
        CountryCode("ec", "Ecuador", 593),
        CountryCode("eg", "Egypt (‫مصر‬‎)", 20),
        CountryCode("sv", "El Salvador", 503),
        CountryCode("gq", "Equatorial Guinea (Guinea Ecuatorial)", 240),
        CountryCode("er", "Eritrea", 291),
        CountryCode("ee", "Estonia (Eesti)", 372),
        CountryCode("et", "Ethiopia", 251),
        CountryCode("fk", "Falkland Islands (Islas Malvinas)", 500),
        CountryCode("fo", "Faroe Islands (Føroyar)", 298),
        CountryCode("fj", "Fiji", 679),
        CountryCode("fi", "Finland (Suomi)", 358),
        CountryCode("fr", "France", 33),
        CountryCode("gf", "French Guiana (Guyane française)", 594),
        CountryCode("pf", "French Polynesia (Polynésie française)", 689),
        CountryCode("ga", "Gabon", 241),
        CountryCode("gm", "Gambia", 220),
        CountryCode("ge", "Georgia (საქართველო)", 995),
        CountryCode("de", "Germany (Deutschland)", 49),
        CountryCode("gh", "Ghana (Gaana)", 233),
        CountryCode("gi", "Gibraltar", 350),
        CountryCode("gr", "Greece (Ελλάδα)", 30),
        CountryCode("gl", "Greenland (Kalaallit Nunaat)", 299),
        CountryCode("gd", "Grenada", 473),
        CountryCode("gp", "Guadeloupe", 590),
        CountryCode("gu", "Guam", 671),
        CountryCode("gt", "Guatemala", 502),
        CountryCode("gg", "Guernsey", 44),
        CountryCode("gn", "Guinea (Guinée)", 224),
        CountryCode("gw", "Guinea-Bissau (Guiné Bissau)", 245),
        CountryCode("gy", "Guyana", 592),
        CountryCode("ht", "Haiti", 509),
        CountryCode("hn", "Honduras", 504),
        CountryCode("hk", "Hong Kong (香港)", 852),
        CountryCode("hu", "Hungary (Magyarország)", 36),
        CountryCode("is", "Iceland (Ísland)", 354),
        CountryCode("in", "India (भारत)", 91),
        CountryCode("id", "Indonesia", 62),
        CountryCode("ir", "Iran (‫ایران‬‎)", 98),
        CountryCode("iq", "Iraq (‫العراق‬‎)", 964),
        CountryCode("ie", "Ireland", 353),
        CountryCode("im", "Isle of Man", 44),
        CountryCode("il", "Israel (‫ישראל‬‎)", 972),
        CountryCode("it", "Italy (Italia)", 39),
        CountryCode("jm", "Jamaica", 1876),
        CountryCode("jp", "Japan (日本)", 81),
        CountryCode("je", "Jersey", 44),
        CountryCode("jo", "Jordan (‫الأردن‬‎)", 962),
        CountryCode("kz", "Kazakhstan (Казахстан)", 7),
        CountryCode("ke", "Kenya", 254),
        CountryCode("ki", "Kiribati", 686),
        CountryCode("kw", "Kuwait (‫الكويت‬‎)", 965),
        CountryCode("kg", "Kyrgyzstan (Кыргызстан)", 996),
        CountryCode("la", "Laos (ລາວ)", 856),
        CountryCode("lv", "Latvia (Latvija)", 371),
        CountryCode("lb", "Lebanon (‫لبنان‬‎)", 961),
        CountryCode("ls", "Lesotho", 266),
        CountryCode("lr", "Liberia", 231),
        CountryCode("ly", "Libya (‫ليبيا‬‎)", 218),
        CountryCode("li", "Liechtenstein", 423),
        CountryCode("lt", "Lithuania (Lietuva)", 370),
        CountryCode("lu", "Luxembourg", 352),
        CountryCode("mo", "Macau (澳門)", 853),
        CountryCode("mk", "Macedonia (FYROM) (Македонија)", 389),
        CountryCode("mg", "Madagascar (Madagasikara)", 261),
        CountryCode("mw", "Malawi", 265),
        CountryCode("my", "Malaysia", 60),
        CountryCode("mv", "Maldives", 960),
        CountryCode("ml", "Mali", 223),
        CountryCode("mt", "Malta", 356),
        CountryCode("mh", "Marshall Islands", 692),
        CountryCode("mq", "Martinique", 596),
        CountryCode("mr", "Mauritania (‫موريتانيا‬‎)", 222),
        CountryCode("mu", "Mauritius (Moris)", 230),
        CountryCode("yt", "Mayotte", 262),
        CountryCode("mx", "Mexico (México)", 52),
        CountryCode("fm", "Micronesia", 691),
        CountryCode("md", "Moldova (Republica Moldova)", 373),
        CountryCode("mc", "Monaco", 377),
        CountryCode("mn", "Mongolia (Монгол)", 976),
        CountryCode("me", "Montenegro (Crna Gora)", 382),
        CountryCode("ms", "Montserrat", 1664),
        CountryCode("ma", "Morocco (‫المغرب‬‎)", 212),
        CountryCode("mz", "Mozambique (Moçambique)", 258),
        CountryCode("mm", "Myanmar (Burma) (မြန်မာ)", 95),
        CountryCode("na", "Namibia (Namibië)", 264),
        CountryCode("nr", "Nauru", 674),
        CountryCode("np", "Nepal (नेपाल)", 977),
        CountryCode("nl", "Netherlands (Nederland)", 31),
        CountryCode("nc", "New Caledonia (Nouvelle-Calédonie)", 687),
        CountryCode("nz", "New Zealand", 64),
        CountryCode("ni", "Nicaragua", 505),
        CountryCode("ne", "Niger (Nijar)", 227),
        CountryCode("ng", "Nigeria", 234),
        CountryCode("nu", "Niue", 683),
        CountryCode("nf", "Norfolk Island", 672),
        CountryCode("kp", "North Korea (조선 민주주의 인민 공화국)", 850),
        CountryCode("mp", "Northern Mariana Islands", 1670),
        CountryCode("no", "Norway (Norge)", 47),
        CountryCode("om", "Oman (‫عُمان‬‎)", 968),
        CountryCode("pk", "Pakistan (‫پاکستان‬‎)", 92),
        CountryCode("pw", "Palau", 680),
        CountryCode("ps", "Palestine (‫فلسطين‬‎)", 970),
        CountryCode("pa", "Panama (Panamá)", 507),
        CountryCode("pg", "Papua New Guinea", 675),
        CountryCode("py", "Paraguay", 595),
        CountryCode("pe", "Peru (Perú)", 51),
        CountryCode("ph", "Philippines", 63),
        CountryCode("pl", "Poland (Polska)", 48),
        CountryCode("pt", "Portugal", 351),
        CountryCode("pr", "Puerto Rico", 1),
        CountryCode("qa", "Qatar (‫قطر‬‎)", 974),
        CountryCode("re", "Réunion (La Réunion)", 262),
        CountryCode("ro", "Romania (România)", 40),
        CountryCode("ru", "Russia (Россия)", 7),
        CountryCode("rw", "Rwanda", 250),
        CountryCode("bl", "Saint Barthélemy (Saint-Barthélemy)", 590),
        CountryCode("sh", "Saint Helena", 290),
        CountryCode("kn", "Saint Kitts and Nevis", 1869),
        CountryCode("lc", "Saint Lucia", 758),
        CountryCode("mf", "Saint Martin (Saint-Martin (partie française))", 590),
        CountryCode("pm", "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)", 508),
        CountryCode("vc", "Saint Vincent and the Grenadines", 1784),
        CountryCode("ws", "Samoa", 685),
        CountryCode("sm", "San Marino", 378),
        CountryCode("st", "São Tomé and Príncipe (São Tomé e Príncipe)", 239),
        CountryCode("sa", "Saudi Arabia (‫المملكة العربية السعودية‬‎)", 966),
        CountryCode("sn", "Senegal (Sénégal)", 221),
        CountryCode("rs", "Serbia (Србија)", 381),
        CountryCode("sc", "Seychelles", 248),
        CountryCode("sl", "Sierra Leone", 232),
        CountryCode("sg", "Singapore", 65),
        CountryCode("sx", "Sint Maarten", 721),
        CountryCode("sk", "Slovakia (Slovensko)", 421),
        CountryCode("si", "Slovenia (Slovenija)", 386),
        CountryCode("sb", "Solomon Islands", 677),
        CountryCode("so", "Somalia (Soomaaliya)", 252),
        CountryCode("za", "South Africa", 27),
        CountryCode("kr", "South Korea (대한민국)", 82),
        CountryCode("ss", "South Sudan (‫جنوب السودان‬‎)", 211),
        CountryCode("es", "Spain (España)", 34),
        CountryCode("lk", "Sri Lanka (ශ්‍රී ලංකාව)", 94),
        CountryCode("sd", "Sudan (‫السودان‬‎)", 249),
        CountryCode("sr", "Suriname", 597),
        CountryCode("sj", "Svalbard and Jan Mayen", 47),
        CountryCode("sz", "Swaziland", 268),
        CountryCode("se", "Sweden (Sverige)", 46),
        CountryCode("ch", "Switzerland (Schweiz)", 41),
        CountryCode("sy", "Syria (‫سوريا‬‎)", 963),
        CountryCode("tw", "Taiwan (台灣)", 886),
        CountryCode("tj", "Tajikistan", 992),
        CountryCode("tz", "Tanzania", 255),
        CountryCode("th", "Thailand (ไทย)", 66),
        CountryCode("tl", "Timor-Leste", 670),
        CountryCode("tg", "Togo", 228),
        CountryCode("tk", "Tokelau", 690),
        CountryCode("to", "Tonga", 676),
        CountryCode("tt", "Trinidad and Tobago", 1868),
        CountryCode("tn", "Tunisia (‫تونس‬‎)", 216),
        CountryCode("tr", "Turkey (Türkiye)", 90),
        CountryCode("tm", "Turkmenistan", 993),
        CountryCode("tc", "Turks and Caicos Islands", 1649),
        CountryCode("tv", "Tuvalu", 688),
        CountryCode("vi", "U.S. Virgin Islands", 1340),
        CountryCode("ug", "Uganda", 256),
        CountryCode("ua", "Ukraine (Україна)", 380),
        CountryCode("ae", "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)", 971),
        CountryCode("gb", "United Kingdom", 44),
        CountryCode("us", "United States", 1),
        CountryCode("uy", "Uruguay", 598),
        CountryCode("uz", "Uzbekistan (Oʻzbekiston)", 998),
        CountryCode("vu", "Vanuatu", 678),
        CountryCode("va", "Vatican City (Città del Vaticano)", 39),
        CountryCode("ve", "Venezuela", 58),
        CountryCode("vn", "Vietnam (Việt Nam)", 84),
        CountryCode("wf", "Wallis and Futuna", 681),
        CountryCode("eh", "Western Sahara (‫الصحراء الغربية‬‎)", 212),
        CountryCode("ye", "Yemen (‫اليمن‬‎)", 967),
        CountryCode("zm", "Zambia", 260),
        CountryCode("zw", "Zimbabwe", 263),
        CountryCode("ax", "Åland Islands", 358)
    )
}